# Generated by Django 5.2.3 on 2025-06-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=255)),
                ('ingredients', models.JSONField(blank=True, help_text='List of ingredients with quantity and unit', null=True)),
                ('steps', models.JSONField(blank=True, help_text='Step-by-step instructions', null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=30, null=True)),
                ('spicy_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('meal_type', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Dessert', 'Dessert')], max_length=20, null=True)),
            ],
        ),
    ]
